### PR TITLE
Create meeting-02-*-2016.md

### PR DESCRIPTION
**Pull request by frankcash**
_KOOL-AID MAN STYLE KICKS DOWN WALL_

IT'S TIME FOR ANOTHER MEETING

### CODE REVIEW

**Comment by gsingh93** [comment]
One thing to talk about: hackbot posts to github when it deletes a post, but I don't think we can do more fine grained deletion, like comments.

**Comment by nsgomez** [comment]
Spam prevention and reviewing join requests from potential spammers should probably be discussed during the meeting as well.

**Comment by iangcarroll** [comment]
I can do any day, so those with tighter scheduling constraints should probably propose a day.

**Comment by frankcash** [comment]
I also think we should create a clear policy on how to handle reposts (maybe I missed this when reading what we already have)

**Comment by gsingh93** [comment]
One thing to discuss about admin policy. Should the number of admins always be an odd number to avoid ties in votes on any issues?

**Comment by frankcash** [comment]
Let's do this upcoming Tuesday?

**Comment by SCKelemen** [comment]
Subgroups

**Comment by frankcash** [comment]
Subgroups are already on the agenda.  I think we should about them first
since we keep pushing it off.

**Comment by iangcarroll** [comment]
We've used a zero in front of single-digit days before (`agendas/meeting-01-07-2016.md`); should we keep it consistent?

**Comment by frankcash** [comment]
feel free to change it

**Comment by iangcarroll** [comment]
@cydrobolt proposed using Debian's MeetBot for meetings (and his viewer, fedora-infra/mote), which we should discuss.

**Comment by sckasturi** [comment]
+1 to MeetBot

**Comment by gsingh93** [comment]
+1 to MeetBot

**Comment by SCKelemen** [comment]
+2 to MeetBot

**Comment by rubinovitz** [comment]
I finally passed the .coop domain registration process for hack.coop. Trying to set up a mix between [Node.js Foundation](https://nodejs.org/en/foundation/) and a social cooperative for hackers. Will try to swing by meeting and get your thoughts.

**Comment by arirawr** [comment]
@rubinovitz awesome !! :octopus:

**Comment by iangcarroll** [comment]
Notes:
- Create a list of subgroups. (@me)
- Test comment deletion w/ hackbot
- Require the number of admins be odd (@gsingh93)
- Setup meetbot (@gsingh93)

**Pull request merged**
