### PR TITLE
Create meeting-01-19-2016.md

### PR DESCRIPTION
**Pull request by iangcarroll**
## Info
- Where: [##hx-admin](https://kiwiirc.com/client/chat.freenode.net/##hx-admin) on Freenode
- When: January 19th, 2016 at 8:00 PM EST
- Who: Anyone
## Agenda
- Meeting procedure, agenda, and minutes (@???)
- Merging policies round 2 (@gsingh93)
- Subgroups
- [your suggestion here?]
- General Q&A

### CODE REVIEW

**Comment by iangcarroll** [comment]
Suggestions for a date @arirawr @frankcash? 

I think @frankcash suggested Sunday, which works for me.

**Comment by frankcash** [comment]
Sunday night or afternoon is preferred.

Monday is okay too but it is MLK day in the States.

On Thu, Jan 14, 2016 at 2:09 PM, Ian Carroll notifications@github.com
wrote:

> Suggestions for a date @arirawr https://github.com/arirawr @frankcash
> https://github.com/frankcash?
> 
> I think @frankcash https://github.com/frankcash suggested Sunday, which
> works for me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wearehx/meetings/pull/3#issuecomment-171743723.

## 

Charles Frank Cash
FOSS Programmer
cashc@acm.org
https://github.com/frankcash
https://keybase.io/frankcash
https://github.com/frankcash

**Comment by gsingh93** [comment]
I remembered some stuff.

One thing is some of the stuff we talked about last time never got done, particularly the hackbot post. If you remember any of the other stuff that was talked about but never got done, post it here.

The other thing was discussion about how to work around some of Facebook's limitations. These aren't super urgent, but I think there are two things that would be nice to have. One is a log of all reported posts, the response to the post, and which admin responded. This log would only be visible by admins, and since I don't think you can do this with the FB API, you'd need to use a chrome extension.

The other thing was to have some log of all the posts to tell when administrators deleted something. One of the problems of HH was things going missing randomly, and it was unclear whether the OP did it or an admin, and if an admin did it, which one. While we do take a policy to close the majority of the bad threads we see, there are going to be cases eventually where we need to delete, or where we get accused of deleting. In those cases, it would be nice to have a log to prove it wasn't an admin, or figure out which admin it was.

**Comment by gsingh93** [comment]
It would also be nice if you guys could leave your thoughts on the [subgroups issue](https://github.com/wearehx/policies/issues/12) before the meeting.

**Comment by SCKelemen** [comment]
Ban Logs - Maintain a list(database) of banned users, and reasons why, also maybe have an un-ban date. I think this should be public.
Looking for Hackers - any thoughts on why we are still getting a lot of people looking for hackers for hire, even after the name change to HX? 
Mandate Content Policy Citations - We should probably require citation when removing posts. Also, perhaps it is best if we have some cookie-cutter, standard responses for closing posts. 
Create FB Group File for meeting agenda addition by persons not interested in github

**Pull request merged**
