### PR TITLE
Create agenda draft for meeting #1.

### PR DESCRIPTION
**Pull request by iangcarroll**
Needs more items; feel free to suggest any. 
## Info
- Where: [##hx-admin](https://kiwiirc.com/client/chat.freenode.net/##hx-admin) on Freenode
- When: January 7th, 2016 at 8:00 PM EST
- Who: Anyone
## Agenda
- Finalizing and merging the Content and Admin policies
- Hackbot stuff
  - @gsingh93?
- [your suggestion here?]
- General Q&A

### CODE REVIEW

**Comment by arirawr** [comment]
Not sure if this belongs in the agenda, but we should discuss format of the meetings themselves.
- Should probably be a moderator
- Should probably be specific times that general members can discuss and ask questions
- Should have someone taking minutes

**Comment by vishwin** [comment]
I've brought this up in the channel yesterday but we were all ready to go afk:
Channel mode +z allows for "reduced moderation", that is only those voiced (channel mode +v on user) or op'ed (channel mode +o on user) can directly talk in the channel. Otherwise all messages by other users go directly to op(s), simulating a moderated discussion setup.

**Comment by arirawr** [comment]
@vishwin So ops would get a list of messages to approve/ignore? If so, sounds good to me (someone should write that somewhere so folks know)

**Comment by vishwin** [comment]
What ops get in that situation is a bunch of unglorified private message windows.

**Comment by iangcarroll** [comment]
I'd say we should hold off on setting any moderation modes unless it becomes necessary. More work to post people's words for them; if we end up needing it, it's a command or two to set it.

**Comment by arirawr** [comment]
Sounds good to me.

**Comment by gsingh93** [comment]
Agreed, moderation modes are unnecessary for now.

Just a suggestion, if there are topics specifically are going to lead the discussion about, you can put their names/aliases next to the item. I.e. since I made the content/admin policy PRs, it's probably best for me to at least intro the discussion about next steps/things that need to be fleshed out, so you could put `(gsingh93)` after that item (and the hackbot stuff as well).

The hackbot stuff that I want to talk about is regarding transparency and moderation logs. i.e., a user deletes a post/comment and blames an admin (apparently this happened in HH), how do we prove it? Other issues include how to deal with reported posts, i.e. someone reports a post, one admin handles it, the other admins never see it, and if the admin thinks its ok, people might think the admins are ignore them. We also need a game plan for implementing the other useful Hackbot features (see the Github issues on the hackbot repo).

There was no admin response to [this](https://www.facebook.com/groups/wearehx/permalink/1714093802168471/?comment_id=1715748522002999&comment_tracking=%7B%22tn%22%3A%22R0%22%7D) or [this](https://www.facebook.com/groups/wearehx/permalink/1715772932000558/?comment_id=1715825818661936&comment_tracking=%7B%22tn%22%3A%22R%22%7D).

You guys will need to decide how you want to respond to this and similar posts going forward. I have some thoughts I can share on this.

Another big issue is what to do about subgroups.

We should also talk about some more administrative things, like what types of posts do we want to put in HX Meta, do admins want recurring monthly meetings or will you only meet when meetings are needed, officially hosting IRC logs somewhere online, updating the sidebar with all of this info, etc.

**Comment by arirawr** [comment]
Should also add a discussion on a group name change (to HX, or whatever). Hackers is very much prone to spam.

**Comment by arirawr** [comment]
@iangcarroll Let's merge this and get a link to the file in IRC?

**Pull request merged**
